apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:6HGDiMxyKAux1WlyoiUwbXnPIocp+AXJwlRcVLWgk7UXvK+N4uY5Dw==,iv:+vVK920PG2LujDaPUJF/diP5D86N4rd4YU/hVqt6vn8=,tag:ig9HupcJXlpft5AJyW+tDg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jm4t4kmzv3ecty4ruqtp6mzt76hr7pc5ste38aj6jg9vkgmchpcqz3ucf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTFd4czgvYTExTDBac0J6
            clVRMXkyTmc2cCtWNTBwNU9nRXpIc1RIU2pZCi9iWmJlY28yOWJLR1d6Y1g2dE50
            cUI0K2pLZXhIL2dYNUlkazdXWmZqdkUKLS0tIDhGanVyNVNQTSs0ZVZ4ZWtBdzdv
            dE9zMG9WMXRpU2wvOHhyVlhKaUNsOHMKjT/8qgPvkSGXMtkt4yJMSulaNM8BApNG
            WlZLqGv0SxG0bgskSXoS1svKGUelJzE6iqF3p/Z633t+fWqBk+262Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T15:12:44Z"
    mac: ENC[AES256_GCM,data:EfnY2wZMGcmS+dkGBeDAVD+5+v7lDrqg8F/GLiRDAFLcEf9mxjqfTzybQqeAqgD7GaA/fWVLZ7j/0dsFdvjX/169GXNGKtcybTHjLIjzyrcsbq38zZeyadfw985XViHLNVny8/ojL7jNs8rSKwc8ChRHT7ekinhRX5ja9nwlYqg=,iv:8cpCg2Z/wUkh0Fvaz3rl1KUX+DHi94ORpZ6sIjtmDfQ=,tag:5NkeYKiGXX0z4P2QlvK0Gw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
