apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:U9xcnKMY8ZqcsA/7nzsIf4RTWjDrh2H1RalvvGJ0xXNh3yd4t43xtg==,iv:Dvi/DtujWcM5nfwwMmpS0kVop2gE88kL2hrkzdOYMPk=,tag:KZPJCBHPxnbkVJiuP3TfQw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jm4t4kmzv3ecty4ruqtp6mzt76hr7pc5ste38aj6jg9vkgmchpcqz3ucf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZzVMMFQvNEU1MkZpUXdI
            WE5ycmY4aFNERnUvRU8zZXVBRFQxUkpzUVhjCjIxQ3luWDdpYy9rSlFUbjB4Z3hl
            aFFVcDUzVDhKMWowVmxTQVVTRTVUTWsKLS0tIFlQeGloSWFXS1dURDFBMUh2OEdI
            VzBNN0R2UHdyS1doZGNzRW5BSk50SDAKbzcgVW1VvhMxy64XEISfrnlfvNbZAQ0A
            mfKMeZRhQiIMbiHTNLGf0FNT9p8N2dyOxz2ODHl9+qo2Da5RIer/rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T16:51:40Z"
    mac: ENC[AES256_GCM,data:XkY/kQFaLPYb0CjLu2unPh1Nc6a4TLLkmAl0IDOlA4dLsfFlvV/YOwLiDGdRZAJVdPgCh+PJFze97vKr5GGHmCYg22LTI9TZHCGObyz5HEzZtsSkl3OmFCJqgFBKIS+H8D3CjET9j6DoEnZ7C1S8xJiRYZDngAKtuL5Grxh5wxo=,iv:zymWvbxSvAa2x4sNA9ALeVUb9r/FAoLXsmbdGUfABdo=,tag:693nX73op2VtYkUvWvkKLw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
