apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:e+1X2JP0lzWSls01lecDXqaHzUIlIhkeTBLZCNKyJXpgOb/e/0Hl4Q==,iv:U3okP+fqDrQwfedP5mZoRTiUSK91aq/MOEot2CvuR8o=,tag:bfU/GW5l2ZffGDiAmkvBTg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jm4t4kmzv3ecty4ruqtp6mzt76hr7pc5ste38aj6jg9vkgmchpcqz3ucf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmc0Qvb2FkTVVHMWlsaC9j
            b1M3UEZUY29vdjJzRG1hb1VGbWFKSDlMRkFBCmNZdnFMU1RBaEYxcm9PNWFyNFRm
            dEsrdUJEc2lGUzMzcDkyWlVzZVNSTGcKLS0tIFZPRmVkMHR0MmpuRUVtaTVQNUxJ
            UTdxS2E2cnViTjA5RmNZa3JldWQ2a0kK0SKKmGhF/kuigI7mEeaBMJolnX1KUwWa
            tAxcNsoR7rRr5jXL54ms3RF48SlhjEi6SQrtcwLCwr1TEBKgVSx93g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T15:39:22Z"
    mac: ENC[AES256_GCM,data:i+I6+aZMBERj8ojgqZh5pgWyV94h/YM9wjestrN+veGZzFqu7+vf/Nx2KD8zLvXHyQWOANHHWQY000gzv0JnVXamvVkUzGsP8ogQaox0LC7in27pU77SJDDZCwZCObJmgwJCyyS5fHzSp5N8ZyD9/FCNFcdKy28MCXBtZbh7Sk4=,iv:GF128zihK3l8PhvfLpNcOtKf72tSeUUZPzHXPH9OA6A=,tag:BaYJ7K2HHIB3N46f3xj7GQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
