apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:oIcQeiaFwRBydqRNu1f1wmUaXuDQ38lu/YNNAOk9pcwiiZM7aGZhkw==,iv:vwUaGm6jci0xxFCX//NRuUgr3KuC9XwdPrlswuFQCg8=,tag:1i5bQ34f2aHgD+EIINhTrw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jm4t4kmzv3ecty4ruqtp6mzt76hr7pc5ste38aj6jg9vkgmchpcqz3ucf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQWhpaHo1aUdqK09WS3B0
            dkloQ0JxelNnMkNxc2lKYnkxRTNyMXF6bFNBCkFLN3ZHTktGd0h3SHVjeTlydGJt
            eUVDVlhNdHhFL3Vlb0NTbWZzMFo1NVUKLS0tIFc4MzU0M2FVeWJmbWpaclhReCsz
            TndOM29jNHVBSEVvTjJPMHFqb1VSeFkKRnh1Y+kTmUGQCYOAp/qtRe1Uul1rDV2J
            XDIwlCo3DyAOQEQPO9YPUYJSTz2N0jW2s8LJ0ZfEG3LCnvrDRJRXSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T08:36:55Z"
    mac: ENC[AES256_GCM,data:zaHSH6N59pTXriEg5oCI5TAMqr28BG65yvgaKPzjfiMYrW/oNZzYYGGqchzpVxPIuceHJoZxw1U+3xMiEWS4uyCP/LVYP4dTqC3PNEKaYuXdWwpa10ab8q7QUf2pvFRlnIlnWuSqa9CcSOeRVM8vpR3msjb2i0P1ppjxchm4Q64=,iv:ywF6fjMFW+0YFeu6e7Bl9wZvoNgl9WOZnRYIqtTTrXM=,tag:tqduxTHURgFAkqt7TELzag==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
