apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:09ZIIvgsPlrtGRoKDPhrYDXn6B4t5FubfNln7Fdcm/lmyLIyxMALAA==,iv:rqsVvZQHyxLpkkyCIYEnf0Ez8Ma3DTFkPS55Wi5g1lk=,tag:Rgt49savMDY4CthLKO6XXg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jm4t4kmzv3ecty4ruqtp6mzt76hr7pc5ste38aj6jg9vkgmchpcqz3ucf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWkxJamtDSGE0SnlRc212
            TGw2K2E0anlzZ1lZRnN2WFlqN1dSYTVQVm5JCkhUTWJmbGFTdG5MVGZybk9uUi9l
            MHFwLyt6cFhjVEYrUE53MzhXdjRQV0UKLS0tIEJUaWpUL2FBU2lSOWFrUTVYTi84
            UmNLYVNDbzFRT1o2a1h6SDZRQjBSV1kKQra2dyMux0YXFSF8DAmEeiTNiNLmbFpS
            hTwU8HIoZbwLKCyw6iRg3zVH/YMOORnPnPQ5qYWnZ8gerrQIN8YcNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T15:46:04Z"
    mac: ENC[AES256_GCM,data:BaQIVCs/iWNBBsemH3oNFNcQnOLyqceT7neNDeRwdSBPz0AYtEpKxBnuy5mPyg9g415wj9GXvgzz+A0GjnSMzAd8gx4+BZdT8Hub0fNRX0ymTIlqgT/TpPh7b1lk+xTXgiowLlG2DUj8xu0y19+Jzy9vs2wWmuCTjK4Q99aievk=,iv:jR/jJnVpG5xX0R+eeuDYp8q3DA9zLlHHZRQg9KwgONc=,tag:OE1tkl9iuAUn3RgKUjpQpw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
