apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:yJaxpE2vdESuWyDeGoNJ6IS1LjrXgK17TKCWvMYERMfm8z6sajIbNQ==,iv:BKZt2eMDobiI1e70A76+plaJjGH5Q5yG/OEDNm5gJnI=,tag:k7UyVhuGw9HA6LDu7fAZng==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jm4t4kmzv3ecty4ruqtp6mzt76hr7pc5ste38aj6jg9vkgmchpcqz3ucf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbHJNenpwbk11UVlXU0lO
            b2lDRXZmeGRaczF5NEZ1dnVWRmhGV3VaWFU4CkQwbVhuZnhLNVdLaE1uWjVEZTla
            Sm1OQzN2NE5rQWNzcXRMWUdxK3dQMVkKLS0tIENGNlVxclhORVFYSm9SaE42NmFx
            Rld3Z2hKUzlwVEF4b2U4R0hudUxHSVkK/2hqJ8/JXz2+SPYXWFSOxZDj7a2xrM2r
            Iso+QPWHh4POaclGfLL8wL63ECiYopOemhqHftJUiT/se+MBUhp2Jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T15:42:41Z"
    mac: ENC[AES256_GCM,data:FIDp0fA7nb5P+J6WCmNd+Tt1xfL8NNfStxyn2dP20iC7BwNIMhtTZiC4tb1ZjGqmSocnLGh09u1uELu46+Ngzo8fYntAZlraC6oIQkNIxMXZdSg6lfxeTzWmVaMKcNIx3C1x4WH3DCHP+9Lb2FTpOFIZWWPa+5Why7XTbvqmdKw=,iv:E1ByHXm+eHJz2tcru/rm8HWS57w+kIyvHz0cPwe0rNY=,tag:Wg/7PlUtG9mIffWFvRuynw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
