apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:QPG+WTx2KaIxDfaQqYlIeADlPJjXVm98hoKU/F+Ox3jTHmzzFdtLYw==,iv:ueDZJ6E8Si8zDUlMjnSGbPU659AmNrZ0XSwIejNPRLM=,tag:xHsFgobxqIyyX5k4J0EPjg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jm4t4kmzv3ecty4ruqtp6mzt76hr7pc5ste38aj6jg9vkgmchpcqz3ucf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5T1g1YTNHdUNHeUc4amx5
            d2pOMkJlY3hFZkpGbjBPa0JSNUJOcG81dEY4CmlvN25LN0QvMS90d0tsMVJtNkd1
            cnF4TERBbVlEZy9yNnhqeXdGaDNndWsKLS0tIERNNndUUzg4R3kzVTBoajVnTnhH
            SzNMRUdEeXVXQUxiVERLcm1ZWnFKb28KRfs21KVZTNeIifA/kwAsv3dimSyZQ2jd
            zS93OyONbo2JtZGUWZ8+1X5XPihty3KnwDGka7wTAfLFA/AxRI1Ffw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T15:03:14Z"
    mac: ENC[AES256_GCM,data:OsLaVRPDtSL9gXqd2kM/pNNV2wyBcbx08p+s8gzqCWkM4cxlFEZ5lZ05UftSrINh+7OVwOw4DBgfHUNXFDU30yjEJegoePAKmuO76POHfQBpq7rOX9YuDXFBUrUE3ZzSLK8iBMWea3VqOa52SkMrTnifZrgdLtieL8bRE/1Y1Ao=,iv:nvNh/xZZ3ccatYJG2gfDCBIv5sthOHEFssNCuQyOYrg=,tag:l4Z5v1PJ4SBwdy3WQ2DU9g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
