apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:zWoJ4nW+uBQe/oMAmlTSoVQtdZmrIn2zdpF7P6lxGr+f0e8hL7vgUw==,iv:F6xtPZQJJnsz7qQR1vSV9/2eiaTJo03LbHF2SID/Yt8=,tag:GBu1d7Zh79R4M53kDJ5Fkw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jm4t4kmzv3ecty4ruqtp6mzt76hr7pc5ste38aj6jg9vkgmchpcqz3ucf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZXZlME1UVzZNeHNkd2VM
            TjZpQ2lYYU1VdHBNZGlpWDc2TmxsUWRMWFYwCnlsaHZRalFwOXplYStldjlPZE1v
            Rm1zc0NET1piaUlYeE11OXRUWVhUc00KLS0tIFNGUGRVajVGUzE1YmFTcUpLNjNy
            bE9MdzBORTlpblhkRGhmNlBZdGNydk0K5BQb9I+bSCxDBax6EtN9xRscOVjulRSr
            SKnnuJ6pCPx12GPgWZTZF2lNmHMOPIlH6s8Coab582MtLECj6n6SoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T07:57:18Z"
    mac: ENC[AES256_GCM,data:fTRJZjEpOSvI1q8c3xMQQ6hkYQxpeu+d3L54JQ7XOuW2ALYIHZEJSF0OBAa7VspCLZvpvaoeq+wc0WxO+iV1t5ZaW1lUrg5LT7eVNcrqKU/Luk74bxcZHP8cZGYuPahkTj6ijZ71ZFRKcj9Eu3VMza6e5OOp+91DcK4Tm1Es4VA=,iv:LB2kzoIA8MnDgBs1FxcpIo5A1TA0g5+Iu49AvxoxtJE=,tag:cFKPuxOU2aUvqWhqkV6wMQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
