apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:UstrbdJDy7w0puoBFcycj6/KcQ50KSRXQNQgj9Y1R6TSpHrTiarwFA==,iv:QnDAj0xvTwzDvrWzTDPZ7qWzRROjSJs+Z+pBL9yUNPk=,tag:HAqTOJE0OcsHcMQlOy5AWw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jm4t4kmzv3ecty4ruqtp6mzt76hr7pc5ste38aj6jg9vkgmchpcqz3ucf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrYTd2WTJYMlBvZDU4MmU4
            UFJLVU5pbjgrNkN1aEZJMzMxZ2lrMlQ4SW53CnhoUjFGSEZRZStDOHpNZ2VJelRE
            RmNLR2tyWUswMXZyNS9zY2lSNzd0aEEKLS0tIHFWVUV1Nnl1eDk4emJ2Zlk5cDdS
            MFpoVjlJUkd1cjIvZk9BQWNCcUc1M2MKnLbVnRFsC9RO8WTkEpldr9OQWgUJGX8+
            m4TYn8HzTiikPiBSu1WV0f+8pwTqqZ7kaecyrpQqdzP6jCF/Pg04ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T16:48:46Z"
    mac: ENC[AES256_GCM,data:/ikYOQXUe0cdQ7uRouGMZDxkxF7NuTzCowz/MJu0q3vDFr4lUs1BT7qmyeC/UeFbXp3dgSe8Vr5b3d3BJVYIavelBisCdg0LAcNGqppdKr6O/rcUT/B8kGOymyFTTFCrBMXz5PkfFWlOG7cYCV77dXxlFSVcXbPJAGeqGMP9gS8=,iv:hncdQs4WOf+7qXN+md5Zzi/dbq1ppk+NfUGcwOSmGcM=,tag:Dg6miwxfnH5N8AIH3oRYag==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
