apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Dmcdl8Sa0Z+wexJte84sJO0xbjYP9yoKFq4kT5rAPXegdDcAdOPmPw==,iv:Pai619oSqU+SMYnMMvkfM7kzpJuIgMufLob6gvZEUYk=,tag:z9NqnLHO8i3P6CSsh09bSA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jm4t4kmzv3ecty4ruqtp6mzt76hr7pc5ste38aj6jg9vkgmchpcqz3ucf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXN013alZqRjFlSVR1QjRs
            Q1dNVTJRallzQ2lxUkdnMndtZm04TnBxZ3lFCjJwbm9hcmRhODVpcUZUcHkybWlu
            V3FneWRSWHlWSkliRTN4TG90Wkc4a1kKLS0tIHZwd2dFNTNybGcrVVFxdndQTnNM
            dW9vYzNBeTdoYUNtNitNb2QySFBJbUEK7kEQM1bbycas7uRKF2xOGyMhUNwY7bis
            tcrr1vZxj281wmToU+tjgmOOd/64vQm/i1yK9/Eoh5s8TAyGkBJNpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T15:58:05Z"
    mac: ENC[AES256_GCM,data:EdYK9xFMcGUJlhHFBNMQYTbaq9PD4iFe1CcXrxL5qh0Ai6+5/R68YbBRhKH3m2pysaSv7F1NgnMdwLSc0Jha7tLDBp99VVNYIq/fHGd/Xpjj792YoqfAPonP+e3CpKBvfHsCwH6vkJT66o8X3kJnTdtOqE839CHiofDfGZ80ESw=,iv:sOVHHF8C44mZYowa1WVRY5mbJhINolCooAHlHLXbAuA=,tag:Q1b4k0yhhkqpnS9ENkkBrg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
