apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:eOTafPVk/joODwNozy1c/jVa792MriR+akFlcyAe56hoibNOelKcUA==,iv:R5Um4u1D7SvyYgx48jB1Jt6yXqhyQK5ROwQb3HLC75A=,tag:Xo6zQGPZ4JyvQFLsT2cqvQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jm4t4kmzv3ecty4ruqtp6mzt76hr7pc5ste38aj6jg9vkgmchpcqz3ucf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiajM0U3IyZ05CWnBBQzl1
            WWd2cWREb1MzdW4rcUxTazVRbHhjMXQzOVRVCk1IT3RqUEMrT3o1VWIvL2ZKZzh2
            U3I4aHJGYlBqTVJ4RFRRNE5jTEUwdVUKLS0tIFRsZzEvZDA4Z1hZWVovR1dCWkQr
            UnU4Z0lERkNkSCs1ckFySzRSZEgwQk0K2TmV+Gc+dYypJxYP/oHGKm4/wV/0U/ol
            cHujGzwktTGNjukO3iJ60RKsAiFpWO8DYgfgn1g3bfrVfRGBbBg6kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T15:28:45Z"
    mac: ENC[AES256_GCM,data:7fJjGqjWRucImq51eAiQtLmlAGX3OWVqkbt3iKhDawhj4tPleACI6TBZuUqK4KXZUqqe3weplGKPRxQlnziENWStLS+42pBPa2mOWw9O8awHWVyNEFuO7oMoWdIb+edcfOfryLQht43wpolt2kE8SJ8dvi/FJNYT1Fjqkjyk628=,iv:DaJnYVLBH7lmanbUVAKjeO6VYkp0qZo+ReJfFYFWcgA=,tag:SBaFfb/Q7n4IXOQXMGtiIQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
