apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:skKg0emNAYZml+qZjlMfXC9vcxzp5lisuIZicrb8OGzWr1hHmzs4ZCcHq6UJk1YTLVj36mxFWdIJGzKNIKlVo23mNbvmM6S2yAa043zDedMSbRHVGytm9C9GteOVccL4KViQRTcDMAsBGxJpN6gzI/K9T1F4Ih7AifVSK6MHKlb0RoLiyc2SkLuURI0TWz1SOd5TDST0xxb/GVj0bs1NPGWs7qTYiHq4WrGcMvjrJq/0WA9EP+0xHO52kedxuX3AhtaITlgoHDC34gBKHtYoV9O7tbvFEIfOnHyIBY9NWB/1s5qjmo8wROH1pCMkE5lDgqd1k9dBPVIgaoPjmsmt1NNr2T24xDWUjoq4qT42dR7c7wPWhSIOUCcmF+6t43+v,iv:VanUAiNHtpFr6Askvg2FJRTyJmrhoFOYnGTbspRHECA=,tag:3VvoeDw/YZcLr5IXad7Asw==,type:str]
    identity.pub: ENC[AES256_GCM,data:LeET8ahRHip+nMXtI81TXWCbXkFXZFkgrFEQnXVA2S5eE5g3s8HQ65leyseX2+mJnMwLcWkcVBnjcgkhFO5AULiHgM9cVqV2kG2xqFIGeOspGId/Qke72x4E9qhSw+5KMXjHSsDTXwTecepwibsuJyUif3dn8M+AXZbN8Rjib9usZ/QpVHgvSYJ2PFLfWSqp6oD7MgiD0vKjgWMUwk7avmxSgaJqIOj8DNe5so/XVXVyqVgrVqLT6HmYxHfX+XeKOOEQ58UOiT2VYKd5Iw==,iv:CWh39R3Y7htLuXxOp4kOP+xlFWnYBT8LyAkveGTKBxY=,tag:VSnO+TMSopKwvGFoQ7bevQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:tTqCibdfe+NriQxE8PHmiQLrKgqMFGVhpyeXJ2mbG8sSjmfzS8AA87W/0CI53p+njURZ8G5Bi+QcijcnFARsJmC+BFYOd6/YX1bLCK4Ejkhj5D1gp9TbC5PCL+NXy3xpktSN07IAmSu4PGzQzxQdnRRmSN7cdIFA0mrS5f+net7MqD1/NvxH0diZ0SPcZI/0LMsNZ0NvFrhqH3XFJxMbB7UxrtZCrLqn3uxQ,iv:7mH9Onh2lS4WuJ50vR8txAPgGuE0XteW1foAyju9uec=,tag:VIxw8g2ca0ismx3ao+MiUw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jm4t4kmzv3ecty4ruqtp6mzt76hr7pc5ste38aj6jg9vkgmchpcqz3ucf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVjU4SXJ6TWpLVXJ4SytG
            NlZyQXNqMjV4amxCUE1Gb3M0S3BtVzFlVlMwCm40MC8zbGFUODI1eHQxN0hPSTRG
            MjZENEc3TmxqWjR4ZituYUtyL0VTTmcKLS0tIGl4Sm90bEp2VXZyQUlCMUJaTGty
            ckRvREo3NVdCWkpSQWJHVytydnNDMVEKjno+wLMDXAXMCV3fCxHMEIXOLzmjSLK1
            fW63vJMb/f2h1GSrS4d1n8JNz2pXyKizmiNuwrm5M2FHdJEZY87uMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T16:18:07Z"
    mac: ENC[AES256_GCM,data:+qcwcloFpUxGvhezWpT94NCYHkbLdZ3CNId+n9UOyL4Qr1uGsYzr2VPjd8uYB9iH2mIp+75Oj7PfUOSc3JcApRxSF5USTdeKwf+N/EoCwsv8f7dtlvxxYduCxCgGxQ6ezryvV36SqLzj9TtG4Je9tWJ25Xs61fDDmRi4JD6hSec=,iv:AGH+AASbw9TSyVe5jK6jbvxaBLaR7JWeUhQxEHdo3lw=,tag:SlPfjtthaShqx03MYQR8fQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
