apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Kn2NzIL8LCmsfovq7WVS1HqjsHCCehpIXwVg/wYX9Qvg2FjQbF4sv7MouE0L7VlcUXbjOFdQyoIREkflP+2fqfR8EGjKnYlDuiAF8/apr47Ew93LobUxUzo2JnwrTvgORGqPNRcGYSdZoC1ZgDb+ba+ZasIubXTCZ/zvDkvVX+JnYDSaH94h9wSokCTl5giVthkGWHw78cl8H3/Ey6pqfpRfODB1BR5u2O9csYF/3uWhhkD2Pjix8KabFMi6NT8ewQ9TiSXrm7EssBl5H+tndlJ+7UA/GygR2gGne7jh+dvjfUKpaHoeU6LfW09XTXH0KgA7gotUHO5kpRyNCe9MtJomerllB5R8D6F7PuhDwdIWt+7DbB6fR2nqj2v02saU,iv:F3xn9Lfxm6xIeYa0ohzIV4uJ8GvSfakh7RnAbDE314w=,tag:uc+HdEemDyROwxqTR3D+Wg==,type:str]
    identity.pub: ENC[AES256_GCM,data:ki1SCuEFMhrNa0DM4s3jMKDztHPsCoZPd62YGOlpqP8FhEnFcrG87sF0DTHS92/QpeNjpJMn1cKMP++NEJc8wAeLWg617OgCwU1B7a7k0z+oj2bfJOjkZadUaBY9LTINwhIEvSJYUu/QhCaTm5uR6MBpGvS9Utj94pdLviBUBjlB5GA85o25J+zH8Mr/FNAtvSFkc/jUkMDafVrAtcMilRg/k0LJR0LXyyAsSm6cSNQKhi2qEHlCN+dvYOHrzEoB6EVS3KYmXIddzUMZMA==,iv:O5L1YMxY5+pFBvf5AU+Vopqg6/mcklGEFDYT+XhqfgA=,tag:i4msqESz/K3OtNp6B+7hxg==,type:str]
    known_hosts: ENC[AES256_GCM,data:LIa5ipQ3uMPdt8f6iUiAN2cydZhw/G0anwAQF3NoVyYcfKydqoTYr2erlnc2i2XTQsEFV6a7+Id5C+qpTmGELfmzV1gvvxOZmwz8qEN35QLH0jXhjOl0ewf5zNh3hTrJFBfV9zfs8mNH6HDmFL8dOPoNLBV97BOiuCzDpS29v1PQbVjF+voOjEvrSoBdG3fHBEMEkKJNaiGaDV4nDD3YhWJT6lbCfXZ1Sfd0,iv:HPH7jUtMgp98bZyYncccl616qQwYX4fPlbShM+cWx9I=,tag:xLHrMBECGBqooBbjEYtdRA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jm4t4kmzv3ecty4ruqtp6mzt76hr7pc5ste38aj6jg9vkgmchpcqz3ucf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNEJPZ2tUcVMzZ05DTXRL
            dHp6RmpBUlRpWTBnWUM0OFQ3M3o3NVF3eEVVClp1bUdVNVg2cTlTaS9ha0V3eWlQ
            NkVORDVKZnZuSTRhK0dGT2ZqOFBMR1EKLS0tIHBvK1RFU1l4WG1UWHFEODlFTUJa
            aHNyWWdwU1NXcWFrbzBqWDZvSHZHUzAKz/NJ4koZxIn3nvoSdzQF4vTUwmdMigTQ
            fIi1d37y3MOnpJ9sFxFgxOX2KbYbr4w6q0avW/1Maj+vs2FrP710aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T14:14:39Z"
    mac: ENC[AES256_GCM,data:obWe5qmDU7AxX44vBDJ49nB1xjpwL0P7HsJkPKMR1yZYk+Q9eUsUVhLy148xb9iay4Kq1DuIm+N92ejFRsOu5Hhw8MHug4kA8wZX65Ky3UWxkcwq4dmqd0TMVu0J5RrXb82EevK8HyizkVoWHXcrB6Nl7isXNKLvQJWzxicad8k=,iv:uRadJYfrKN16s63wZ8PBXKbh3rLQ2wCHuOcRszMUQ0o=,tag:1jYSDJvSLbJHUwxG+OohBw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
