apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:vwPVj3zF/L5nI48PfKjiHHr6bJpmLXzwGYFue7IFsJ0v/j7n8JSEcNWfDD6/one73CfaLlDfIVvpqS1McVNely0RXiImvRJG1ZN7jltH0WgicWPV5MFcynTR3K1Hk9xVH/c36vMKqfsnPDCRr72bxaccoga/RhWK2zt/ApGuUFgDT0k5sp4CTeEh/CkimHhtf5coeZyf91Sa0l+zRfnHcHEmRDvjlNKK31UvhMhQdZnZkQn98EUz5Gy1o+lZGipYHQK8e7laiMSMlov9pk1G8oDq+V54pZ5PiUtZzxeswJ2IEvswlKygN7hkOdDTapzZFVF+POt1S3xzJ7d4WcRdkixt8u+nONSVjotiXWG2PeBvJgGWfZ7RMxtGsi8v7NN4,iv:TpnQYukyPi0OVV3Wb9JasV+onBqGdDnZGdhssi3+pCU=,tag:TZxfxhYtNmho+elDZkof8Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:k7sFojuJTFGxQwedA8SzViIbwp2C0g3ftf74l4jqynJWYgmSGGkI5o0ip6Kl0Np6OWunulGbrsnSNVYhgNo5QV+6CwRuS4QjCbWkUcE4nWAJR46Sd4l13kDaukJe7JTJuuoD4pkcMIdBdeyyyyQ0cXewUTmuMlj7VNLu87bfIglWmEu3tIvtt8n6MFgnHC3E53E2z7SYH4WwQ5rkLelkluiajm5ic0iZMD90Fd3DPFpA2uM3c7hd9u9Ya1+rf5Gb+o3T8wUFZ+KSF/kwcw==,iv:f6dStE/hfNELzLAXrdniOGpoKt0T5u4fO/HVkNy66gk=,tag:90gfW6iuhLjY4oPoCeanoA==,type:str]
    known_hosts: ENC[AES256_GCM,data:SL1OsDM9H1tcrMELtBJ8OTTDe/LrHxAaK8x4MKd593PbgXdSrcznkVQxdH+PGHtBrMnOzMw6vMbli90MmuNCBE+vv6l9aNm+6FvZllKdz29TSr7yH4rRFWfxlHE/auDvkQp/w8ejLQlBePzIrngMQn8mpcWmIc9oRTFHmplNBuDZ4aPQ+8gemck+J0uJu+rtI6c9x5N0w8F2nTMDghezOSax8RcC+hwSwawj,iv:75Z94LFjEoLhrQF7JiI1FaWqCUvFabtLLBST9EE4qvQ=,tag:K7LIPb1+fDY0J3IWPebecQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jm4t4kmzv3ecty4ruqtp6mzt76hr7pc5ste38aj6jg9vkgmchpcqz3ucf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSm5wNjM0N3NRZ0VXdEVi
            V3VTMUZKajhsZTFuOGRDMEZTRmREcXJUdENvCnk2WVBtcElIMkVtY2x0ZjdKMGIx
            bFpISzdtdy9JZXVNclV5N3o5T2lvSUUKLS0tIHh4N1lzVWNOSHE3WkJHdGd1Rmll
            enowOHRBTEJtbm9zWjBZZ1FSMGc2N1EK8xHsKmVANVaLSbM6o1g0sQ8mqN3RJ7Nt
            XyKzQwnnxM8N7vZIwB9dxWWpsR4ihhzaixMkV7QDANCku2gVT6uesw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T07:57:18Z"
    mac: ENC[AES256_GCM,data:arsdDQYGo9dXjJMuJ+aifpcCN8ry/PZ9fQyYOt4s6Fcamnw6UcVJAd9rlT7wP8ILBx56G/AH3fj6CqodaHlaVI7bgPCzupz27e+TlhrYmm/cjQeUMWGnoeZvDdZC0bsJxyAbezLhI8ujpOqy7oLOilk0Fe4fbj2IVSvpaFmsHi4=,iv:/LzRBdV+wTTdLLWV0urciuATayGmgzfhV1AtAnFMRIc=,tag:/AKQCNP+s5WSAfwQIW89zA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
