apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:3+scP59trVwJom/YpkJMsIb0SqsoBI3j1INhH0ik7p1EziwjIEURkZ81nDBixK6Jpiv3ViWDLCrfEZ2QvB4IRIyVgf/N1qt+oIxTtTOzvgjcMN9pf6r5Vlz2+SC9K0M02DjJGwfiA89hEkJsj56tg0pxvp5nD0WmOLPfNs0V1AG9eAOTFdXHHKBynmUqsATda1+C7XDtsCbwP5fURTwGfTGge6KgDDH359aF/0wBU+f/ljyCHr3kR9O1GS2B2NU1XD16Fc6uZGnNfHgzrViEEV3RO8Wrn3rh4sUtDbeSemT/PSDS0SzKtp7AcD17/xqrbhfuK6/jsdenigyZ7JCGEne/NPUG4Lvit8lQwNh2vnFZYeu48KoVcFh8DLTTgkdr,iv:HK6mCei/8r6IVLNGubAYl8wxht4G2nZrQCEXDi7fN1Q=,tag:Ycvt9DugfmTuZ1R/UKYKLg==,type:str]
    identity.pub: ENC[AES256_GCM,data:kk566/Sa2YxQZC6u2xrCvvF572BdbLWi5+SnIzWYpi14tW6pkwnEwlCKBEpyjAw0y1zEYJWN3ZGM4B/18Qi69rW8upwNp0E8fu49pvaiV+waZaBbNEugdKooQLFO2Q+dBg6PZ5dZculLj3JqyEni4iS7fU6TRpBb6YoOEKulu5vPlMm71IGy452ry2gy1Vy9T/GoKGOhFnUlZTa7hzLV2/Rr3WMeUPiPzoTiVC7k9gHxV0ak1WZNva3y1LxQ/RqC7I9fGvgVd1muAxCgTA==,iv:90l+nAJ7BE3KYU/eSuRBNUNNVuVjiI1+KgTFcL1Vx0w=,tag:c/Xm3yqeHGfSCJneWjNX0A==,type:str]
    known_hosts: ENC[AES256_GCM,data:DfzgQTiu0mum1Rk74Ypth5we2FD8OD96Usm0r/mFhSsHKi4WQlr0qssvast3VoipoNCzRKnHm9t+WgpFxRWzbzRytn704wcDDH1quKjBekTR5TMWjBWuOHo2jl/HCqGQEL5NxMmlp65oN7Kq3blcvI/DqoCNNjxf4Djk0NgRRs4liS2iidY+eXefxi4gfG4nAFdqduyjaMVSNvxLDvhWSUMhW9eP+6ofKtKP,iv:DgXoTxdmz2uAQiU0vemO/KHrxi3FFfNgoX0dMsnQvXI=,tag:aRjBRKNVE2GVEx8+ZcFKVg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jm4t4kmzv3ecty4ruqtp6mzt76hr7pc5ste38aj6jg9vkgmchpcqz3ucf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrR2pqVDZpM2FhZ0JsWXN1
            bUhLLzNsZHZYbzdYV3hTeWU0dFFvQVgySEZFCnJqTXh6VEpmMS9HNWp1d3VpRVZX
            cFRHMUZpSTNOenFJTHBIaEZYWDh6MjQKLS0tIHEvR3FtdU5XNjh2YjVQV04vMS9p
            MHlkclZKYklFd3RybGtQeW1oK1ZBTWMKV/0R0t1TWWA2s3zCEOyuM3p5xYAX/HSc
            g/aj1oA1r+z+1rgsxWg2301+MnhsT0fHpSRk8KTfXDbhYDo/nreBeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T15:58:05Z"
    mac: ENC[AES256_GCM,data:RZSvP4Shw2G3a7ZnseuGwC2pjWSjUAVGOk00liIFDjFpmFPQzG91uvUBFtlo57ZwWx+Z8SO4Z/hwB7Mxg/xU1giYfgEnhT+87GvMrc7ldzYCrKcT5pMMn4FCF73dsOGVpdSYtUvqqs9U7gt/rP/aKQ/dSeUm3PGZf2q1ewy6QhA=,iv:DW4qrvSIqF8CXUMKOV/bngmHDXqDnQB/eDxHPhrRHMI=,tag:IdFw3cVY/yS8MiBJ22s1vw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
