apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:6Sg2WYP14PKXHqTqeCN3fXbrxEZClio+zeNjkho6AIm9rdSAcWFGh12rACebA6rRnIsnBBcHiQ2vwDgBln3AeAki1hIYW/PhDCW4Ns0uHmoLMuqIW7FzNqOTYCKkSidhSSlYkGZQVEfLQqrzfZkUQxL7vxpz3QAdUGfp37cvE59InlIPztAEqB2l2KLaZL8EldYecVRF3zmHRvk5csh4N1HxOQ74T5vxqJdOEmnQd99DatcCJaDbtQjRRYHBqnVRTskSal98BBHEHiMM5TpEzgpKMUjcdz+Vwsl1YeUtKHuD5x0H/hGdXGDMqB4LO5FVDNxN9dop4JsR2Qc/ilWzZ1EQsiEBxxsgezbcnnIGWFaLF4AKTW/XBjb7A9q5u/S5,iv:8FjKPpQ2LUhQbnN2iArrvLzbfCxelLF8prh8Xy0iy8M=,tag:1coP0niQLUpW7XTvSXCePg==,type:str]
    identity.pub: ENC[AES256_GCM,data:Qm0E+zcYp88lEcln9rX921DAfhKMFsFF4wK4byV20B8V/HQfCg0bxBoFoqX5cL+Q4dMmlQBq8tlX/k/vFUXGYKlP3UP9iIeNbpwOXmkmy6Xq0ns14E9oqsGVA2Tq5aUTW5PAFB3ye/OlpRchzxbvgFcHJAmb9exUmi/N8qNPIIhJ+S8xfQKZdiuTs+4z8oo/ftK3Ty1Eklh7rPctlfEuq2YXO8TvZdM0/d06A8kAMG2MkNj8AecvjMcsBSqM0v0s2Jo8lcCUT1kDebso2A==,iv:jnPWziMKn5d2bgFKdvd0fsQ8sIBMwi8isSTR/dva1Io=,tag:g26SlFusLjSoyllRYOvU2g==,type:str]
    known_hosts: ENC[AES256_GCM,data:UDjDLmtzsD3aY7oVJ8HoKojamaiR9mTvV6r+4ugkyEEwGs1brBjH+PU4Sy6m7rjhuHcU4LHYBhTSlOmuU2dKLgpmHyRY80pjtecnoaGHqaFnay9kh70xX/PVGGq2lJ4YM4pGCGlii4/bkrtm9SkmAr7ICirAL+QIKse733zk74Zh1MO8HfxhYSPyy77GxaWMZccFeYyFsyPGqrlWzwtKDrrmT5ZXzk6oR905,iv:VAuogdVehv44//ev/7tHugberSu6O/FTAGC9u3bA6uo=,tag:+iIXHvHfx8jgUvJjfQ5lIw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jm4t4kmzv3ecty4ruqtp6mzt76hr7pc5ste38aj6jg9vkgmchpcqz3ucf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRmxBcEhwdGNscVFsTGhn
            MWtYSHE0Qm41b0RMSDBYU3Z1S1MyWCtOZnlJCnFkWjd2SFdIUFVaSUo0bHIwWGxE
            dkRmeWNHNFQrSU81R0ZUTlJNUnVDaTQKLS0tIFgwYVFWRzRXTGdWbExSOU9hQjdX
            Z3JxM0RqdnJHeC9GS0Z6eWVxa0h5Z3cKxuek6D7+Pz80Ag/QFBhzWLfC1r/Ephwh
            noG5zxKX02tWyfzUWepenTatI51Y9yJbRCp1ba3/IjyPoveHQ6cV8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T15:03:14Z"
    mac: ENC[AES256_GCM,data:ebtOnuk9zIkvB5iLb+KFkqninQQ7lSUeDvL1jm6Yx3t2cOCdqDM/Xgy2V+85FxeAmG1UwHnJN6wcY/wi3QhSWKyO/lxNvPeEg6XA1b179kshMm0/kSrMSXfFg/t5Tc/ayRmhOFOUKqugPXYYP93nr7afBFUiGkiknGpzzZGwZ3g=,iv:DMcgkwakirV7pL8lWqOF3GeQtv/wD5D3uT14It1LMdM=,tag:LJmcHgWbZlIcO2MtJgPlXw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
