apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:qCGFP9vLciXlS9yZTW3dKnwNtUpI2OqcQLO5rT/BFCQiz24ylHWccMwA5XMjgM6Rxxm3HAFd6t7KUCwYc3hsng17XsVXiQ5CMQ4fek76E9beKR98GgGtmYC91AwZmMVk4HlZoNIDFs/ve8/Z4q/dvvmfWWEPulyyPX+eTfglXILA2YsiiwVuUvbmI9CHX/e8q/eorYMQCKR4SCdI73hAuY25UIN1EWewwaf40wE297M1HjBWUNcBQ+OjnLmQJdiV1bfPlyh2cFQz1Y1J94ozdzxFVVScZX9Gf+pNqPpmg2k8dOfNjjPFdAZUdVXgDyUDFUazlsRYW+LCpKypqeCnMPe6GHLValUt5S6z5X1gMXg1+K027HYRJkOzNxTuL0qr,iv:gN3mmYt4xzpMaUwJqrwmZgS3LAtfPRQ/KQIZL2XA3Bs=,tag:iEIFhHRVjSlyMTUhLbTkKg==,type:str]
    identity.pub: ENC[AES256_GCM,data:pzF3f7icMDBsaplh3fSKZfbrqhELotky4wNlR+TT1fG9itoGPjBd1q4GMsaUTI5XjoZVinMIOeHePaoAoM1Gp3bb2mVYKhDje5YTLieXOPsQmQ106xunAm2QaTDQMdMSz98YEbV3Q7ssneZQ6N2Z2lQ1P9ng4ZmcG6DqL9ey9mG/8WoDe6pIxTkXOPyUHE5ENVOC2fiKZvr+cKCkFXOF5NV/Nq5AT6rJLmbPDn7ffRwFM6TLmoC4HFgHmfzLzxgTjdlv9OYJS+Sil0bR5A==,iv:RBIGIxmMjkrevDfebqlGaaUg+Wur/cY4yTuTjy5VVlk=,tag:VWQvDgHyLLf4HfmBONJeYg==,type:str]
    known_hosts: ENC[AES256_GCM,data:RlM3pGgU7PkPQqgZwt2k3wYaTJ7jruVgvFzr5GryxDjF1h4OgnlTODTOfvaoWbafF3oIMDUBWfBswjtnhYSKMQ5A8aDU/B8H2A4uQTJFNw54QXE39nyQP1gI4aIGRUAhJdyfmwxHfqLsnF7zvUoZlNw6OARBkbj585ulGPbqbZBBnujdGS8rY1ky6z/VlYAJOEYTCo/pXLaFtEpG0XtpavVLlgOCON2zkhXd,iv:xQhlhZY8YmAj8iSsb0+j1EPd7eEc4AZdF72jpAcwo10=,tag:U8fiP9IKPBKa+R6nLwSqNQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jm4t4kmzv3ecty4ruqtp6mzt76hr7pc5ste38aj6jg9vkgmchpcqz3ucf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwT2RLaFNpUXVTcE13NlBo
            QmxuTDFKbUladStzbUV4dUJBbzBoY1lZaEdvClJvZlBkSklNNzhoL3hMVlAySGp6
            emlhdk1xN1lBT1pmaWdUWUNVS1BodzAKLS0tIFNWQ0RhclFYaEdsK3N1VWdkK1ZK
            SDN3YWtDdndHQ3FwcXV0VnNrb0lQTzQKg04D+QlA6qaqsO3WYqePG4tjpCcIxjA9
            zYv1UozsX4hpjndN8h41Tb/nb5stm+RPHA6k0zVZID+CQW7KIIiQnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T16:48:46Z"
    mac: ENC[AES256_GCM,data:LeZN7DwcCJrlCO6muZ4nd6zDOXl18IeWe+cPTUD0OyExjYDF5AVIJ1Zdu8Iq7ZhVvHoHO8qES7TEQhFBxaIDbmOVor7K1kzeLgqAuVgjnMDP1uBxNpevEBJXPHdJgZAdTK4Ng+XrDbt1FrqsfgDFSsgvcDhBu8HuFWuG4B5z7FQ=,iv:Z28WMq86vY2qvjg6UpDtXTrp6yX2TBmskxxJLKDfJbA=,tag:iZ7j9iBZXFFSvBSOIs/uMA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
