apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:l4Gbi+HKI9rXZeviuS1qxMo49misjAlcASw+BdQZQLEiwnfuHiARsKVSQaby3p6BLcg4TJIHPNyALDIFpEbUt4+zEHyodAjVVEMkAvsTODD1fr4gQZkYLHBkV+lMzbo93Jsy6zHBJRJA/0m/MxPUc1k2D2gdPLuKz5WQJ79xHG/vrMhGxG/8A8DbwtdDkYJ2uqdnWYZoa0vtEjY3SFstAsTkG2vP/poEkmt/8wXpwm+hxQ2o+be+dmMwAC2MsgaZ15mBsKDaikeCARof7IedfRRVnPa0cPcylTBlS7x9T6H613liXG79slX9FXp7nnMe6z3P1yWw3K7JcEe/EBawhRQlrTSBAb303Ew3jh4Xpr23DPrQJ5c2JtjLkINqVKiZ,iv:d3f6knGqynnBG22gv18KLp2fAOO4/4Q1LSYoYMUIayY=,tag:xIwOxu+488TXpbaTqeuTug==,type:str]
    identity.pub: ENC[AES256_GCM,data:LZoUVekI0WO5EQ9/CUlsMOeYlp54Actt1fPN1srZ0np3k7iDYW2KsvdoaBlme/B8TiRS5DtkqNvvpJ2Teai7j7TOtbYM/1Al5HpZhgnccPleO1RY0mBJuUpdF8GZUEsEiC3oYgmC7trPeUe9LOXB7DKEqnrPzRVxck0YWjqQY5lFxomD0i1I7LXn6kaLWB8VByMduyh9qwhcwRbWn9uP+pKeV4VEC/IvzFwyGpZjg9HA7PW5aK3C7SArTYZIsedqODu/OgWCXo71xuZjmw==,iv:wtN8GSny/c258A9Nq+uyyZyLABcB0xkIihsJLQQSZHQ=,tag:Ld5xzMh0IofBwWO4jWf5CQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:/Lsj8HWMYrtDfTlvzrgwNtZgqdpnipgGE3TIIkD7UjAigfaAuJmVyEa+g/Zi0Ft8pzhmqt/YQS7RG4syYFJNUhUcsI2SOiF4clYPGZMVlSmLQTm63At/evKYm0uTwAGoO0GXKi4uBmN2RcKoZBKu8EaH3uzDejSnbe6GOEt1cmiNQsjfXsq7ENcq5VmZ3ko+ZvwmWYEZjELM+zDGyJqsG8NXQgBCWg3nngjK,iv:UbxXG2bqY94dVqBVa2b8UhFXuY74OWZCTfzLgP6TYNA=,tag:U38GzlRhXI7HXlBqNtaghA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jm4t4kmzv3ecty4ruqtp6mzt76hr7pc5ste38aj6jg9vkgmchpcqz3ucf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQmVuSmNWQVJqbFF1U2Rt
            enhGL2krY3dvR2lrQm4zNzVHZU1jazZXZkhBCjhzSzlLc1U3SmlWT0ZUNDZVOWt3
            djN3TXhwOFBWNkU3TklQd0htQjhiY28KLS0tIFArTUpHV1pDZTVhTERXWndabE1t
            ZDhBUnZ5MVp6VHRXQ1NOWGV0V2cvZXcK0E+RmPhx5EYPNpNPoKQEngVNDANHMyQY
            Uk5efSwi+Z7moKo8AnIzaDxWtabe7AGPb8vCUkH/se32hfSo7Qbudg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T14:25:40Z"
    mac: ENC[AES256_GCM,data:0y1gvATi5ZF6DnFwt78HPASdCnB8MaVNip9BEncIJz+9nED7N1Jfi2P2IKJ/04dTOgqrGMN5QusA199fYPEmlhA1gNE6JUcwMXZbDafsr79AXfCyMZmKRgCSqhS8qlC0LpKsMZbArF7MblCtCh3uxkK6cG68o+M09g+s970KuzM=,iv:qxBBkADSbujRWguSpV9mbYTBu0+12QWFYPW7Xu/zJfg=,tag:HCHcwAYAqmQsTFp2uiv0Jw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
