apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:kqUcTb64ga2reyBq6tPClV9ddAg4Zgls1lY0Ahuyvyy9FBm854wkFnQhcZVRF3lXMOLVtQ+7GZLOhIGc+1VUFo1oE6wS9J+/3vRYNHSUouwJ3EY5HnWWPemiT2JGQcdU0jjafsE1GX85rc+MRCf2KLaV3EDerx2Qa43evIvUncPPkhmtzPDQns6uJ9cCmPPWL+T1Q2Xa36MwP0nZ4+5b20+PUvXiuwXh/0Oic6FtRq5E8s5sw9tdLSxTh6mIBswezpN7PlsBfAs0q/sLGZlMLXNc2sTm+juaCo38Nm+/srpQyjA9SzTuIG+7d+F3Z4mLJvKPgUslds7GUgG4rQZtU/2iwpLunSImrLjS60jjSpXdJNbX79//7o/IEcXxg2vq,iv:MTilfdYvp4fbtNtLzcr5R63QWh/x9qzay7E4AJSq9HQ=,tag:l9Lc4HFVleSvrCe87BEp5g==,type:str]
    identity.pub: ENC[AES256_GCM,data:3HElKW2EeUipaCP63w41UfKtoVe2aN8KcGgKn4p+NwSU1hAXHCCfzcO3OULCcMQyRzq/H9Cm9JyGoFufhBYTDdw3FlRYea8yefF7vjBlhxMg2YUFKvw+3OyRiVR56XogSVSlzU5iy7oARGzlPh9+cIbWfd2HDR+yw4/+2tVinO733TuVWJWq/g2c4XoN9Lf5SBuZmbRpGzdS50Zzqj1FmtB3xg/sEOAhoDsIDOcDmp6jNfRKT8bl/Qmb2HS7mHk3t2VJCBdNQhAYX8TdAQ==,iv:TNSA+X+hAyPKmW+uNiD7du6vWoIxoK79bmpFir663y4=,tag:uZipd+YsgPrL6XrduzBS2A==,type:str]
    known_hosts: ENC[AES256_GCM,data:7s1wky0l3pua1xEe/ZVa2v/e6z6iF+JI9cS8AOdesuZUZEl6l1cY5GLxRgmQKMBt7+i6YlAz23be82E4SCZhfnn4zp5AxmLverQwF/RUvkYh0QSqRE5H+BKSf2vhLyiK+L0SRxqdIPhZI890Ve442qJdtdEjEGBR92gw+UdAKbZosNAIZgCYHQIdvgMwDCnOeV9owmrBjxc8ZwcGOFbhZBarx7IhTReBm4uU,iv:cgxALrAFEXvlhSDCJe+5V2SCCUT3vB+V9t+NU4A+uYY=,tag:JvmN+Bta51v1d7jaS+sfeg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jm4t4kmzv3ecty4ruqtp6mzt76hr7pc5ste38aj6jg9vkgmchpcqz3ucf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVUlnN2tzRGZLRVNhZURi
            VTBqcU9CM3FRcWlnTWlCY3lLbWh3ZjF3MUF3CnJtdGxUNHBvK3FaS1pPSm9DYkpi
            T2FBSnJpSWR5M1hTSzJwL3EyZldjbTgKLS0tIGhPL0JpOTNzQ0xmaldkSXRMTGxI
            WkxKcHowSWpxQ0dTQmVnTjhBQUZJNW8Kvy9ekP9smrgDbWRgssF+C16e2b1rWR+4
            uSYzQiojdr8AzCc4xDvStziaCawRooPfCv2w9of4+0RPbaYYkp0nHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T15:29:44Z"
    mac: ENC[AES256_GCM,data:KXUoNQkO23df55b6UINIEBCZXEbdnrlH/XYu/DqnE5H9oG7vdNYNFdiHagLi72T1tAmhkX1EqAQpeEqgGG5OC18U1jgWDOfTwz1E5LRL4Sge0naFNAjaPZhJ5UsiNAanlPtER1oaDxJKio06UnpASD3X5+1/el+3s9+KkpZPwzc=,iv:cKsIt0qZCC8+vi1QvFIU2geFjHq1g43RbF9Je7OZA34=,tag:5uw1hcs+kfg44TknTOK7mw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
