apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:u9aMYNx6+00zYKbVjwIvnNc82lR+kTM5A4wfj9IHnges2GFTa/H+eiS6OQCVdaWQQsYBIQW+sSV5xdL22SANFQtAs5UZhAcZxT/G/eCMtMxuUx8hJGuneEvc9fEaDLVERQE77xmCkE+h3EhnBm9MJZg0BKzOi47zFdss4pBlbxmuS6ZVfdnL+JqTUWKBMXE9x3/uaUPFTt5MYbSMjf1JtdCl3JyKiMK6eVCzRxqStPDjW6MscL46pOLeXQybcBHTxuKU5nQustRBmPuc1pGNCVrUnGr4SsgmFiKfVh+7PJZ0COcuXHczMg5TGzUXjHXmFh5EQjDqdmm7g4Vuv7dgQuJC5gYHAG3T1xDHztfmvX2hQiqi4xFlyrIgvnHe0oFp,iv:jDsBo5TGFGzFCRsJMUKtWzyyhB7VHvMK69qaxCiPOHs=,tag:8Jrdj5QAo5dT4nP9cNxI2g==,type:str]
    identity.pub: ENC[AES256_GCM,data:Opymqkv2JUedkIO2KUHQ0mvPaidQrxJcuSJYNEtFeKgOWjtUmrDVRqBIZtP+eRJ59kIjOqwQ2bgCCEq/EIX4jrJwHnrmrZjMuSEE49KOydbsfxa+GHnrgMMgLk+24OdoEbmzOhtglWpD0SwgjPovbC/6ztbNLpTEgzQdqTHEk92bvZrXp4fSwflRrBpvDUug8JV/9PdBYBGfqXGHW63ywd1a1pOXzPx7lL07kthIxgnO27Np2odYh8qjGosegRBNMC3nh3E1wNtVCsojKA==,iv:FOxjTnviEmLfQ0G628GXN3qqFhhbsuNtSqglfvnlXas=,tag:eQC3KPe4t5VNV7fivB/bpA==,type:str]
    known_hosts: ENC[AES256_GCM,data:l+R8rg/hEaY5/fqdvGYpU1aUvTLYoDgP4aABFJ8tm/dfYJZ/7RtZQFamSHOuuOQoYu9D9gm+DdSBYRO0VVWR3rwyrN5r1iwhM5rJFDB9Guyp0nvaX+XyIWS382YfKWosD9U0W+VlhhNMlk4YM7ehmbBRsnZixnLoFCFA0dqF/x45g8Awi0bH1EpqELNwfg2szYjPzIu6VUNe+5jk9LlnrHBQ3ACzLtlXLWWh,iv:Fqw/4qpXzelDf/KrmX+a3A6pKVZx2oR6EaWAKu+pzDI=,tag:4Qedfz7Eegv9Ngu0Eh614A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jm4t4kmzv3ecty4ruqtp6mzt76hr7pc5ste38aj6jg9vkgmchpcqz3ucf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Uy8zY0E5U05UY0NQTFJh
            OC9ZYnozbnRVWmc1NU9nVEVTVmNZU0c2YlVzCllDUUpEQnJKSkNlSlFBYks0OXFD
            V0trWi9FcTdZVDN6d2hSMXhobVZzN1UKLS0tIHB4Q29TdythdlRyZWVYNXZjdmlx
            alQ0R2lDYXBEckN6bDAxWkdEWWpzeU0KiPQdlIyZ622F2e4mdthSeAEDH0m7d8lg
            x5++S2I7LOvKR9ef+KphouRougDAviq0aPJvP19++qtphwzfjbM3Hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T15:46:04Z"
    mac: ENC[AES256_GCM,data:vmDXuFCsqqccWBEPfnVS69vkAlQoe6tv2v5iqo+YaY3rclp1GktgAOGDEsfwdNg7ijFzWaF5i2bSrCQBs+E64rhD3CH+VoBkdS/LBxnToCj2gg4SV4KgbqstRgqLGjUcbV+dSHhT7mT65FPLL9KDyRqHJ8Nae06+VwRn7ZVVbXM=,iv:TOC7U1MJYhw+L+vbzdSkH8+rcdRrg7uXKG1t8dUGAIM=,tag:+hbAb4e2jjhwx/+F8CSbhg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
