apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:98SpNOp/GdSXoKO6cHIgJErPkObdpxDDvCiXgn/7sMicQA5ZkGi6c8+ZSaeVYmBLUpl0zOGCju0E/HyxfTDbgLbZi/X5w9W2PGG8XPdklq7IqdXidJONRU6U3yV2IW0OsiHpzBluSSuwks82erVuRqiefSbkx2nlwULyVSdykbFri9QngeB5miabo9nuL5a40htP9AROkgugnwiI9nlpWii55Wk/x7aAb4Rm+iuSNevAVanVDrDbYIU42V4jaYqXAdwwa8kWtXcRi8ZOG6aBVF8AkzeGpFhnYNHFMBiv/SrIZuLPgcyNjahBBgMdfT81dWCnaHgdC09fH2i2nBVEC4rDXjPubNkyRdwiYNyYKNvVBMJrSdt+Cq6ZrSBTbkT3,iv:i+4AWgSFarCSnhsokkNTF489emLJcfJgPyAH63dbhNI=,tag:AX3HktKUTEd0IDzDyMzRyA==,type:str]
    identity.pub: ENC[AES256_GCM,data:+j1g27YSXNFASxacjuP/bLTJF2WwHPEX69tnYXot1Mz/sG897avjISlYBkI3pr/fo1NT61numxjuzm9MEN99QDn1oYAlwCaBZ6F/AQQoxd594l/daPORCo5A/OkLgUAvnMJyYGhiQHDawjXzcd6+yd5EIai2nEeMhjzqVIR+MKPm0vcW68Duz6OcNPvv4BQ/9GjCwQY07ov00jjWv+zkOljz8AEJ2CS+A5RbGAcRhgkPmbDqVc3/9gqrVT45TyDMkfIqhgrGmtazWN+zYw==,iv:SmFiefv4W4yylXCOSAFZNClA2JOd/7J9f/zno2OZpkQ=,tag:UQsdm7gC+sHcpSqikjuTaQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:R6O998N9myaSaCgY2fwPh460GUu8qJzOqQIjPjV5yg8VFntCBkVBoNcmDCGJZB0Cyc+pusmjuYaSJbQyqSZD0mn2byRs6wxIBLXi2gyN3PZComjEKStpbK5jw1dq9TYBo0RIBb3jOGLZq7IJzLzgkcXGgsbcvhq/mNAdiKn/5GRnHO941w5UvPk/B0YR7E6lOaUnK0NZOpseRLGsVGydt40USgGbUPyvyC3C,iv:FVPptwj2LTk0Vdj+ViPi0LIjWuGdpcGaiVuV05DRtAU=,tag:rqqBUAl15veafIXT2OoOhg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jm4t4kmzv3ecty4ruqtp6mzt76hr7pc5ste38aj6jg9vkgmchpcqz3ucf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNXFhem0wenFvNWdxbDEr
            dUUrSzk2MDY3V0hYaEhpK2JxM1l6ZlJDdkFnCjdFUXRIZCtyTjZDSGt1S1RMWDdQ
            dEgrUHVlUEtjdTRzWTUzb0dvSUx2alkKLS0tIDZlSWNvVlJ2R3l5WEVia0JZQmNr
            Yi9JQXY2M0FyQkhIRWxmUXJNUG9pNUEKXc+xt8qmRO3mOBcz+CeDPmFw0Y4lF7ND
            WwVZqcrYt2peT+CntwGI3bXQOfM5sL+l7qM8XwDLHWQQ2lD5cFpL+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T08:36:55Z"
    mac: ENC[AES256_GCM,data:CyWL8dKscIxSsJUbD2HBmV2LIYWLHwQltaEupaLzrIkf5stsRWMXTH2bUxbUOAjLeSZuFfFTwmkPEw6eajc4tZvhlTrG5piHJ+BeVBW0PrtV66iOOiizJreqJgI5iRoQjGRY8OsE3I5biWgyTBwRWO7xiQNB9Q6zYU8rztigtUQ=,iv:UA7jpf/bFpAijxAqO3tvTJdPrBxmnKFXFI4Yl749yz4=,tag:WHjd8NZ05oV4WYUWi5drzA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
