apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:3kKH3PXPMonRJzLse1zgx7Bc+5fDzeWkqCJ8SHikQ53k7JQizEFQVD+XTK7PTpKt80uFxYiuA9qlf0FzEqRxwMvfjChTfH+n3sCtrOBM/Dzx3Ddn77qV61AL0vWe37bb32CVoZLTj1Y7A777DDfAJHvF1Gn21bLovOaoR0tD6SLn1ru+zn5dQJS0pFaiE6XAJ9aS8o8TwYMzBZQaZnMSRWihJX4bbUhnnxcMhjHFVCPjZdVG0sKliYTkrqSG7qcg79yiVHvFHgFlZAvcuEOHm+OVWV6Gw7laVkSuulAu5FmVvKw4kJbfqNufQq/D7WRdlUisiI3FfQwUTOAqxu021a+rF5T/08RkP5LuqvkW+dfpyHdMArFgaz5Mcf3RldpJ,iv:VtjWxs+FvWABJRHthlR7iQvhOrc7141olEy/2DsHX6g=,tag:OR/TXdw9msKpc5K0Cb7ntA==,type:str]
    identity.pub: ENC[AES256_GCM,data:q9R+cr/BVNTPxfIVw/eWEv1fkElq7qQCQ7hM8Qj4NuDGp51DMksNj61q+yiqdyy0gtj2SDUVOAXr/g2sbKK7v4ljCXyh1biaeaxl9uWaNOxJJVJ88oQOMt03yNGNdCaYka0dP9noJ/wfOMwzuXcWrCmVBNnO/sJ8zZXDrR3BG7lhkQ4ULjXQKqB4LVIdOGWY8uDT/seRslahNEcaiMxtLgE0A7LEottrS7OzN1WiLNCo5oJ8fZ+cnc4rImBUuiAsKgxcTL66jxV7eQD9zA==,iv:VE5dx+FbF1eiKMOHKDhRvXTzyH1nHXGhhFqrUQBMJsI=,tag:bAAdWWac1mMbr7Opt/6a1A==,type:str]
    known_hosts: ENC[AES256_GCM,data:wVPH6biWJnhQZ5zJdk6UR0PGL0MBbHQxUmbMkcVsEdoErcJnjAKuubPy+61/zDqiSbSXWxApE8PDHmFrGMWHqzbbjO032rVfCl6qhQ6CtaacSJ3Xe9zxz8KjP+kIR1Nmasfq6JO1ss4m7nD5jT0KBkMibxSSlOAlAJ0OJBszCbZsGGvrw8tWnnyMSQXNdwc+ddC/8wIsD/Y0Nl2Dyn0mBcmy5CMIeW14x40h,iv:3IBfH7eyUQ/b0IFUX/SUceI+vsdcBlr0Q9Brn1jNTbk=,tag:6pKA62tZAGbiCQKXmRw1aA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jm4t4kmzv3ecty4ruqtp6mzt76hr7pc5ste38aj6jg9vkgmchpcqz3ucf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcFAwYTYyN0RyYnF2NXBq
            NUwzSnVXbkx1MUxlb3BFcUlwSWswVWR4ZDMwCkwrdmJJbXl6NFlRbWN4WGlXTlVs
            MEt0TUt4ZVRPUkdHaGxpU1BCRC9rbncKLS0tIDlZQVpXZmNWTkZNUlBJVUZLMjAx
            WFJFWG8yZUNtMGNRMGh0N1RuR1IzeVkK+ozYr0lOY+2VSX4TRnKChvNfG0zVE9wA
            0G/7Kd7sAM+pQ8Pt/ue75vp3qLrpCafwUZV+AinEMh7rqIpMXqCrYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T15:39:22Z"
    mac: ENC[AES256_GCM,data:e9Qx3tNR6VBimvu7rjT9eC3KR2mdgVlcj8CqIiDv9KLsq+3vxOWqIibrTGXiCqN2fwlxmkTT7E4caSmZEYZ1NOQ+cEM+ENO0SFSSwLJ+1HmwStY8nI24Y2RamvdoYZdk/oAU2aGePWpRfTj0v2SxlKKLCGoBoxTPUG84qyywm1w=,iv:YSrpCVmgm29pqm6q/mSxaOn2i7NJpO9UFLcd8YSFJ5k=,tag:P/lh+TUqxjaHed1sXrMNYQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
