apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:cxaY4nZqlqpl5XhoKujK/xkH7yQWgYru6dMOaQQVneS9nA6L5z/JIxq8m0PCE62D4C7EHRUPXgxDO/NErsdYoX6cRUuLAovAMysdfu7rj4uqhJbrWPH37jzV8tu3kyOF4Q0HPvFBKEMeThM8B5/p5RylVOHkxHZdJRaym78VqFjVdtoTlSSqNRP+aTdSXhGvwz0dKo5TR/BticPtXol15XgAIbkh+XcLBEyDIew6e9wE9SguWHOL97KbDc6C9FqSs57HsNZtVY9UxO4FaoBtlUdFoMCIHqol5F9Efd5NteRNzSRjfeZ9NH/+p7aec55ROALDtHb0fm+6CF80ULKg3v4uBQr8o0WckLcQRALf1K0TY9LEZNhIhV3Sx+Tcbh26,iv:ToaAY/BaooCcgLyy4o+DVUGHjZbI/Uge8YysIXf7eyY=,tag:gJUZnqLDwK+Ho6hB1S0IyA==,type:str]
    identity.pub: ENC[AES256_GCM,data:TXSNGo9B3KkOgFw4UWOCa6t9j9W3iVfh6HxjGc7feEZJUcb3+xwTVJ8Mg/SRoFmsavFtXcQtIGuLvPGBKN7hirJvN5LgarITWBavLoHInOHVlLAqrmNv938vGGSHqn0jJ7YKFBA9yklm1ilcaCeRjJAEz4iC/WyPN9SeYGesdVEuNRNotR/pB6epaF9pxbEwcmtWVCXZz3AlXUIh/oQkSxAY5279EVJdPw9wwuJYQO3r6pWRyNMrXjMP67HV6MG08Ho4ze7pBwCAZPLclg==,iv:EIeRD2jYhZlCJKtYjAb4GEMzZijl4tuq3PQnlWlbay0=,tag:7RjyC+wyuBAxRB/gwgiAXA==,type:str]
    known_hosts: ENC[AES256_GCM,data:fLLVrFsXiiru1Ze+lOt1+pvfUptb2nT/hAJZoMUo4k4gsKQGuVyTyFp40Vhh8x5Q1vMJ+ZnSPcmwYaGkXuDcZNi27EWV9w4bRqP6Wz+Ujtr0OSd8uSgOjBf6Hom01Ut2LpppmwgaSM1DJw3IxspaqLIzn9mXEMypLejE+8Ulng3E+IJ3lyTbu44UiZsdlucr00NEEydNeebA4IYdhb+n1ZwWTUyt00+60kGW,iv:G+nD0p2VHdAlEMdtWK8V27fA6HTi768A9JFa5NedbwY=,tag:UixA4O+GdNB3MPzxmcY47g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jm4t4kmzv3ecty4ruqtp6mzt76hr7pc5ste38aj6jg9vkgmchpcqz3ucf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlYjlYVjZPZTEwRkZIZkpu
            a1IxRStSNzVoaDV3MGl2dVlWQnJUVVVUd21vClpWNVZZZHdvRVgwMFJHVVl4VC9V
            Nmh6TEltUFc3THNrU3VEV1hOV0R1cG8KLS0tICsrTW5oL2tqSWdJY2QvMk82WXhm
            eHRoK1pON0ZJMjNRMkY0dnRjT3pSR1UKNnSwplPGFNY0+6/giZRrLP3ehMhx+cAS
            loTJ7qdD3M8xDwxNvWYUz8+o/lkL9px/VTmfNgJ6whK7TParXjPvIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T15:12:44Z"
    mac: ENC[AES256_GCM,data:6iaoHSloX4+su2SsMcnErvNTyhpRnUNLMy0vahGg943s3Q4oAw3urPiePAQLDZxitVrOKHyMgAaKoGvBjUV0U4/Rn3RHXa2V+QJ07qyG8CaxxebWf77Uw0+xReYhgjBGF3wKyFQajPL4RFDEcinrwYqxlVJ5gTfa1ImlVSKEtOE=,iv:91Y/HUbL9pqg5LhtbBldnpfso627VJMQjoELgRIZpFo=,tag:5sv7K+5p2sUG7MiRzBlN2w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
