apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ImvBz20/tGVPa8JE34spOAJyYdNfcFf6AnfEMnFm0rUImOZIa+NTqgPGB6KngsFUDoUAWzGQ4CRwE7RaW4eGbqT4nJBGpKQE+xCz/M1C2yD0W+OyNCpE5QPDN0JzVFrhGPAC+eaFuqOpLMIa2BeSHx8dkF2653ZTrLlJDoXIS7GAo3+Jk1WvNu2x1/UFLVkbqHFggYcMnP7qi8MX8DjJTGlvcb98exWZxo4rtKmznwy2O640y63/K+d/dxb5xGpt1ML0L3pdKIYqitKzekLeM4g3BfmV1/S64hokr+Hi2ijzycjv/H0hNg5oH9aI6VVgUrJv0G+31NK6sWCMpH5y7PzkXYdc6AxzqvasFYLjNCkJRHr4EWSpgUlGYukpZcj3,iv:HwMl8699x2lmxccoG00lKqZcRsAYMm8Xu9tLa8wOOWo=,tag:XPBVBT7WcMDtuWuZaDyN+w==,type:str]
    identity.pub: ENC[AES256_GCM,data:tsIw7qnPzP/eJyPNxhbmbQ7JyB823p7fi+9SE1SOjBSO408U/rroPTOFehmz1YuSxhjuwN716ijwr4VRGUHudng9aU4ecMhNZDs+WbXBr8QCsKa8tHfriISE86kOK1Bjbl+WC5kZicUC9dL9R9xxwRy5Ndrh8wsOxDI/617ogqJxcgeM8tw3N3Tw9BpzlCee+IcrYA1QrloeVmWD58dpnuvvNmzrWXpC/Ylk3YiGAdJA3Zf86wYNF39Ads7WQdEhxRkQmY0FyEYH6plKKQ==,iv:LtPua8kLsUcZclVxlSW6J5bQwKMQlNhyZGmIMIuKFEs=,tag:kAE+DB+Sb/4c2zbTk0QNHQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:j1PD0ll589v+GeVf8miNL+7L8HSAmqoGq5Hm1A/2xHnDOpEXKIaHXUCJ8qGyKgDPyLekTLH639SpxWnDKBtiyhxS058VDIL9crGIutGYY8MN4Vo4mrTNQGPVWBBgx6OQ19cxdOPYXmJORgdHBjisqYadhAfPzWCo2W05jvSAzFCCk9Ajvn9yFVeQ2AA2Ermi92y/hfsK2EhhbSZGc4J6j6uEAfVwc0289Zs4,iv:t4Cimp7UKwYLt4WqNpv3ZkC/zF7YfAk9kqksOdFJMOs=,tag:Xhjd4f6n9tOoQC6xazVInw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jm4t4kmzv3ecty4ruqtp6mzt76hr7pc5ste38aj6jg9vkgmchpcqz3ucf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWTBhaU5LTEFRUUdKVmdW
            WmlYVXMzZEFlek9PaEdYd2dYTTRzMHFQYVd3CkxQOThiRkNiQ3p5eEU5Ynd5WHhx
            TElrbXJ4bHdZT3lVcXRjTUhkejhncHMKLS0tIDIxb01wRW1GNFEvajN4R0dpQytx
            THJFZlRLMUdNVFhZYk5sbk9ZQ240M3cKFbqdvMZVGlQc5+apC74jrxvowLT27nHv
            lAsDc6FiUolM5Uu3SX/Gui069sOLDqezWiSwEqGcGFuUDrii6yas/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T15:28:45Z"
    mac: ENC[AES256_GCM,data:Sgah9eYZiOBc8tKhG5vRlBdNrwHahNVZar4pTELWu+zo6UGpNzvqO2wL8HL+w6bP8vBs7BgXX7utxG7O0LY1DJLXefsjbXOF8sQUuxmkrYERGR/eL8lLHZSQl3fGlJ8kdU99XfPbzYwlYncUMm5bH4eaTybjJZLfCRjFlMuuhyI=,iv:AK/pFcd/PEtzaxJhCRp6VY/hc15kkIxxFs3LifE8CRs=,tag:bgdPoxUhC44oNALdLhzSTA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
