apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:qWjFbmk7VZaLPT3A6Ow/RKa1zZTJ3yFPdjJPR63lJLpNTa3uWcaFvUFrs9Z2ODA8i00OSPQUw/BgcAnvxQuXA4UVTZY7Pf9VK3F+YI1/OoFUZe2wT71TM6RcfVI5tiWE5Zj7RCjMZUTf21uFFluXv9LQiaJ7g89otlo+0zM4lgK+6t6u+Za6zLatR3bfxqiSAfDdhTPtCFjyvWeHPrCHHlPH8nnn/iau8Y8RkUWyBsOqMZVRbOlVoY3F8sQ7Os+Vt6xmpXoeORkIaGoyao8j7lVeMtnzW0hcinR4SRNBVVRXA99qCpi8ZoOpOX0Yx+oeuHr3qYGZBJ05O4w5r9aoZnYMW1p7hjsvwszFfJocF50sLJtseDbNPJ8TL6cij+yk,iv:V6Pa6Ox79+e/nJ57o1fqc2RfG9FGQ1ZpWABBbaky/dw=,tag:KKAz9b7pzk+L4K1SN/CXeA==,type:str]
    identity.pub: ENC[AES256_GCM,data:ruL6EwMz6Yc12K5tDRY9rjxdPd4m45M7Y3ZSIaxYf1ajb3FmtoNDyJldZGn9MV0W7reF5jGChZj8zPY36g7yvnrsfzUj4W0095l1mL94stc4RmTzPkdS3lG5iM9ErPSQRIFtUTn0+YTC8DdM4oYAESNmrP8/q4wSytQkhVEbMbtSVKBEZEE9A0ohRAA3TXgRZwfpn2/FIpO++TTmDoI+MQyFO8eAstYj1BDaa0WmqPuHx5dDiGQIc8KcLzR+yWr9ieVEBMwFJnsEzHTfvg==,iv:poLB4sCOaxN59FfCU7V9HCuYwsMMs3AuGW680nXlrBM=,tag:6SUaexdT00jl728R955m9w==,type:str]
    known_hosts: ENC[AES256_GCM,data:k8blmN+ej1I8ivIWmDWyg5t5pMfzH6Fe3Gmrj8UZxzCKiAewc34bj9oUi/Z4D13ApCI69jN1vVPqBDztbB0n6geioTrkeNeYeEaWTbLhPAGKUekwNxKiA+4PTSKGTz1AsLGaL620mPxCscJQ4l/L18VwL5my/1SB4cRR+Puyp7zWM9REcBM+rbAbxBdoHohybc/qWp4oMRgzyeWuWPEhI2uSQlZwDG/CWsiP,iv:CZaiIqjHLsGPo5uCfbmW1ZlsB2IReIGttovTq2fF/P8=,tag:3yY8N6/cG6oABs5p/9nSLg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jm4t4kmzv3ecty4ruqtp6mzt76hr7pc5ste38aj6jg9vkgmchpcqz3ucf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUWlJVEdkT0lKRG1idVVO
            TUpaQ2JjbCt1Wm41MnZLZ2twWG9xbUt5VWlzCmFCcVZSdVU5bWc0S0k0aDNGL2cr
            MlBzb0NCanFrSHJWNGk3WW1LWDdwblEKLS0tIFgvTjV5WFQ3bnJqbmV3bWI5dWsr
            MWdXaGFaTGgxL0M0RHdDL1ZzNW5kL1UKH9D5FnbyJGARJAKSPVUOX2age+v+5XNc
            88Kz2NVVIrBfXEjlfcWcl3tKys23w7fRFMQa0KlMLWsPexxSnefnfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T15:42:41Z"
    mac: ENC[AES256_GCM,data:PXxST3YqrD1pwgy3qcwX00A4dc5Reh4HGRn1ZgFhCc9thNo9fj8+YDHNjXQxVEnjwya2T2sejuF6uEzJwWuvy68RNgGoUdhPSjW6RNaf5KLoFcvPXF29gFDCbOP6DjxHKoLwv0xj3SGq1JLCfsyW8R/eKHlj8ARH0l3KGdKeJe0=,iv:Bi8Nrl3K2eMDM1YOFOC2bENQcaTMNQTd7x8LW/4Gh0c=,tag:WpetmggDrVc10aahnOSIMg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
