apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:SN13OuJW4Xj/hklhOMzXWvQAZ52TtW1AoF3wRdulKIF8jtAdD2sBpmOM2+I4eC9niYzMHi++7kJyzGVUV1KaPTwSnoItCQJoB/haWrsQuzd9D/WangJxYK/VlgCg5hqIX76B669bEEKIQwegqYCtqJLu3SGYbQoqTtN4P4w4yfHDw/WzhZI6k0TZ59GI+Gi3eeDoYUyM1YZDAU3NeVTeC8irmGkzcazMZBP4ZvEe7SeKFeXi8DZViQAIGGkoEQlONz726JGdBCdoYAum4q9L7cbQOzx2yxpaeh8JwPD6wWDot01cnQapew0qO4gNB1Sr7oojlVMldgyfs65bekLko0J2JpjiEeBTSFNew69tksg1Vq/ErcDcbVmTfnGKmXSX,iv:hKi+mmQKSJ86ur1hKhAP2ydW8VT+IrfpO/dhvvrj9xs=,tag:pfryP2g4kDi7Rj9BLFuEWw==,type:str]
    identity.pub: ENC[AES256_GCM,data:ffzKR8cO8KZE5oz0+BGCUg1bBJrHHLRSj4dCHQiLPpgzDwV1OkEhQowvqRwWGGlAExg7h1p/mtmglupJ/3rOvRzFRteCKLTZYb0x2AdZZMiYzKW48uFXN0Vec8xy5i+wxnhib38GTe7YRbNKKw0L1Q7lRm1aku1TJSkvlYhOeCxD3oWHF7uyS10li5yZUo5EYW/pRsLov9qsazIBYmasN6w2sm6WPwAUDscsxFUgjOFQ0mVAnJpbdl3tNOQm+8jF7XTBsaAdpC78P/FwqA==,iv:u0uUy/6y7rQNbtHjfqQAyO1Aa4y7kXtbn7XG3+NqnWw=,tag:9xgBJW6q9M8aw32vfSiJyg==,type:str]
    known_hosts: ENC[AES256_GCM,data:NfMQhvXTRr7m5U3Z73y/l11d9opQyZvV9/0UG7ViRy3IzqRO+Uxzyy+LRElt/OZmWLySkqKXqZEyBoF0OkszZ0bPcQM0IVyXBsh+GPSa9uU3DcUQQBGIk6D+Ol+K2GJLRjkZx6tlb//Aa5U52kj1M8q3E4xTEOz3jFmp9K+7hgMH37yixr+cBvrPqyhUEpAr7/L/ai+51XI9r8Vs76d6i3d/YFeeTZdjxY6X,iv:HxUZPZAGaNFe78KQFm1D5NJX5REiuLZyAJq6wGYyAjc=,tag:8Naz9NjYvhxFj1R2AIOIzQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jm4t4kmzv3ecty4ruqtp6mzt76hr7pc5ste38aj6jg9vkgmchpcqz3ucf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UkVMK3czTjllVDQ5MzI0
            TitBYWsrNUMzZCtmN0pEVFZJRVZPMk90djFvCkU5VGx5YSt3VWl2T0cxQ0tGb0dK
            cC9Ia0IrTzlIcFFTNUYyMDA5Rmx5NzgKLS0tIEI1T1dhYlhzUUI5cTg4UTRuaE9R
            YVRaRGJWRDY2emJBR0FtY05ocjBIUlUK/SOiRxjtTPL8en0KkjfKGCnZ6H9xKmTp
            vOWvxRXA95TDJsn2FCiDpRJ5G+A0n3CXO0JBcB5PufvReCl35ZrBgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T16:51:40Z"
    mac: ENC[AES256_GCM,data:s2OEMcHGk/Ff9nhd7GZ6lUyKSMX2enSbByBjSRLzx9FMCeMB2y1Gyi+8jhxAcmf6Ra6usx6Xb00SAH2GIHIXlc7ycAUkJeAQhbfniuJTOTT0hpIzsXZjG3btuEK0CDISePoaheL9heQ4R0eT7F06Ux6WvuzlNlbOHVb+G/iKFh0=,iv:LOaRM+e4zRKfctixNZvxA6XMA+xwoYd/Rg/XoEqbj8A=,tag:qgBzfxBJGaB4Fxv65uSAtA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
