apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:dJLLnlJx8KRsjx2zdeae3P/IsGjAwruMSpygR2BPhdjcIImQr3SplHWnK3Zpoj2Btg+ox+XZVi8lMY7hLBpt/1EfFYCNu6+qnaL6LkpeUVG9jghH+ktb4Jdocv771waU9PAIF/2Qwh/EEvkSRbLCYt6BAnPiKCNoQDcdDo10TgFVs/7t1Tnm1kAVkFsmm+C/6Ufdz9KbOG2KSvMpgzwySLE9l4RomeOYuCmt9Lw3OHgTaKicENgekAR58kUQmfor8Gg0EdICPWcbvaTo6809zZ6rRmRTH2GCWd/NzqpnN2TgdrYCBdZ/60DzPbuso4W+S1Id8CL3FauIVdREZ/3zkzRgUNt9W/5xkn3r+ZYnxZVcHqHHaZFeTdn40eBOsK9N,iv:z7WiYoT2bHllJVQKIa/Pkz/5OtsI93YYu5rRU1PqRcA=,tag:Y5O62aRO5gcziMuWW7GMUg==,type:str]
    identity.pub: ENC[AES256_GCM,data:GN+r+jUax3lEGmCq5CrYMscer3a+ab2GgYhO2KdidJJecGvc1MClXY1GJcWl/m4mQWEZEwprWFeJ0lJ8Itp9NAR9qXFX+JSOiGFzT0VFjaWTzD2Z6AP/wrw4j24gIsaEoNOIaju2IhtKxdU3rqsn62pgWDW5Ky0Mknt2BLaXCIg/G/nH106dtTZjvU5gOj+tKne5a11AlDrbgzjQuo7h0J3iAiG0UhjYYERc8LYqni1kfPBPTiIHV/Zxvq32A0hcYpEsqVBeaPknD6SY6g==,iv:XxtKjDORTCurrFrKyxtmL87dQe8T+J0HW25oKnOmJWs=,tag:eMQ2/uW6R0y4obnvAP8JwQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:2pNfpFjcRnetjdc4oHKR+gdPXduo+20mbD8nOVY58SjuTtbLuPDVQMP31Nj+OLtZ6A0nSb8BGIRZtbeUwU3DcwEy/5GH2vb4iguaLP0go19+8+EWSVm74kKnRR9vci7jba8xIiP2L/VYnUITUSZebATzuARYbW9jjB5GCLzcN+KgHhCWEXh145vSfb21dd78scfpVR4qKXqgrh/kjVFocCrbN4lAL+zzAJ74,iv:XTPKO511RL9y4xmuPj4ifFyQ1+2BZQ9d3SdrJKPeAsM=,tag:ocATDuN0ibYG0mzbZjY5fQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1jm4t4kmzv3ecty4ruqtp6mzt76hr7pc5ste38aj6jg9vkgmchpcqz3ucf7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNnRxZVR5UW9rVDUvbDk2
            UXlVd2MrRWVXdDV3SGhWQ1JucEdHa3ZzZmpzCkUreVRpMFJxUHhRYUZvYnVmcHc5
            YjZHQmY2bVk4VWs3bWlvckVJOXg1eDgKLS0tIGdDbmZvREtRWEhITEpidWkyT3VZ
            ZG16elFUaEdEWG9VQUtpMkRQRUxzNG8K+5NvGYuPqxqXNEt5jpVcKokEAK4zmlg3
            F5RBkWXswPP7SmjhCLIybhjdA0DctOCNSKVz2BGYZEG7w0NaE219dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T14:44:50Z"
    mac: ENC[AES256_GCM,data:N5zACN6b4bnZ+jZtZ2ptHS1mEJpoZj8AARmZ7t9778vCoFLgEqlV8/4FUjadzZU96LMVoIVGpFd9N3hx9zHoxf5kxQKqhlRReVO1Jec1q6VYT62VYooKFYH/d/Ci9JsxYlZmNi3c2Pb1rEUM3ql+0T9GILhnNGCZS5CsOXVAGY8=,iv:mJL75yZwS/Xbocul1EB0BFlU5e1tzPK8coYmpY0nPEk=,tag:rK5MgLuX35iOS04Pw60GtQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
